name: Pull Requests

on:
  pull_request:

jobs:
  Install:
    uses: ./.github/workflows/_shared-install.yml

  Lint:
    needs: Install
    uses: ./.github/workflows/_shared-lint.yml

  Typecheck:
    needs: Install
    uses: ./.github/workflows/_shared-typecheck.yml

  Build:
    needs: Install
    uses: ./.github/workflows/_shared-build.yml
