name: Pull Requests

on:
  pull_request:

jobs:
  Install:
    uses: ./.github/workflows/shared/install.yml

  Lint:
    needs: Install
    uses: ./.github/workflows/shared/lint.yml

  Typecheck:
    needs: Install
    uses: ./.github/workflows/shared/typecheck.yml

  Build:
    needs: Install
    uses: ./.github/workflows/shared/build.yml
