name: Main Branch

on:
  push:
    branches: [main]

jobs:
  Install:
    uses: ./.github/workflows/shared/install.yml

  Lint:
    needs: Install
    uses: ./.github/workflows/shared/lint.yml

  Typecheck:
    needs: Install
    uses: ./.github/workflows/shared/typecheck.yml

  Build:
    needs: Install
    uses: ./.github/workflows/shared/build.yml

  Release:
    # Prevent infinite release loop
    if: ${{ !startsWith(github.event.head_commit.message, 'chore(release)') }}
    needs:
      - Lint
      - Typecheck
      - Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/cache@v3
        id: cache-node_modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
      - run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
          GIT_AUTHOR_NAME: ${{ github.event.head_commit.author.name }}
          GIT_AUTHOR_EMAIL: ${{ github.event.head_commit.author.email }}
          GIT_GIT_COMMITTER_NAME_NAME: ${{ github.event.head_commit.committer.name }}
          GIT_GIT_COMMITTER_NAME_EMAIL: ${{ github.event.head_commit.committer.email }}
