name: Release

on:
  push:
    tags:
      # Semver-like tags "v1.0.0"
      - 'v[0-9]+.[0-9]+.[0-9]+'

concurrency: production_release

jobs:
  Install:
    uses: ./.github/workflows/_shared-install.yml

  Build:
    needs: Install
    uses: ./.github/workflows/_shared-build.yml
    with:
      artifact: true

  publish-npm:
    name: Publish to npm
    permissions:
      contents: read
      id-token: write
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: use-breakpoint
      - run: tar xf use-breakpoint.tgz --strip 1
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-gpr:
    name: Publish to GitHub Package Registry
    permissions:
      contents: read
      id-token: write
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: use-breakpoint
      - run: tar xf use-breakpoint.tgz --strip 1
      - run: |-
          sed -i"" -E "s|\"name\": \".*\"|\"name\": \"@${GITHUB_REPOSITORY}\"|" package.json
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
